---

# for use with bash replace these:
#  os_version: '2'
#  os_user: 'opensearch'
#  os_user_id: '1200'
#  os_path_data: '/var/local/lib/opensearch'
#  os_path_build: '/etc/containers/build_opensearch'

networks:
  opensearch:
    driver: bridge
    external: false
    ipam:
      driver: default
      config:
      - subnet: '192.168.0.0/24'

services:
  opensearch:
    image: 'local/opensearch:{{ os_version }}'
    build:
      context: '{{ os_path_build }}/docker-images-main/2.x/'
      dockerfile: '{{ os_path_build }}/docker-images-main/2.x/Dockerfile'
      args:
        UID: {{ os_user_id }}
        GID: {{ os_user_id }}
        OS_VERSION: "{{ os_version }}"
    container_name: 'opensearch'
    user: '{{ os_user_id }}:{{ os_user_id }}'
    environment:
      UID: {{ os_user_id }}
      GID: {{ os_user_id }}
      OPENSEARCH_JAVA_OPTS: '-Xms1g -Xmx1g'
      bootstrap.memory_lock: true
      discovery.type: 'single-node'
      action.auto_create_index: false
      plugins.security.ssl.http.enabled: false
      plugins.security.disabled: true
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - '127.0.0.1:9200:9200'
      - '127.0.0.1:9600:9600'
    volumes:
      - "{{ os_path_data }}:/usr/share/opensearch/data"
    restart: 'always'
    networks:
      - 'opensearch'
